# -*- coding: utf-8 -*-
"""Google Play Store App Analytics (start).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilhRIeZA2FlLUKf-wr01yoei5EO9KsKP

# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements
"""

import pandas as pd
import plotly.express as px

"""# Notebook Presentation"""

# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

"""# Read the Dataset"""

df_apps = pd.read_csv('apps.csv')

"""# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).
"""

print(df_apps.shape)
df_apps.describe()

df_apps.head()

df_apps.sample(5)

"""### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.
"""

df_apps.drop(columns=['Last_Updated', 'Android_Ver'], inplace=True)
df_apps

"""### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.
"""

nan_rows = df_apps[df_apps['Rating'].isna()]
print(nan_rows.shape)
nan_rows

df_apps_clean = df_apps.dropna()
print(df_apps_clean.shape)
df_apps_clean

"""### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

"""

duplicated_rows = df_apps_clean[df_apps_clean.duplicated() == True]
print(duplicated_rows.shape)
duplicated_rows.head()

df_apps_clean[df_apps_clean["App"] == "Instagram"]

df_apps_clean = df_apps_clean.drop_duplicates()

print(df_apps_clean.shape)
df_apps_clean.head()

df_apps_clean[df_apps_clean["App"] == "Instagram"]

df_apps_clean = df_apps_clean.drop_duplicates(subset=["App", "Type", "Price"])

df_apps_clean[df_apps_clean["App"] == "Instagram"]

print(df_apps_clean.shape)
df_apps_clean.head()

"""# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?
"""

df_apps_clean.sort_values('Rating', ascending=False).head(10)

"""# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?
"""

df_apps_clean.sort_values('Size_MBs', ascending=False).head(10)

"""# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?
"""

top50 = df_apps_clean.sort_values('Reviews', ascending=False).head(50)

print(top50[top50["Type"] != "Free"].count().sum())
df_apps_clean.sort_values('Reviews', ascending=False).head(10)

"""# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings"""

ratings = df_apps_clean["Content_Rating"].value_counts()
ratings

fig = px.pie(labels=ratings.index, values=ratings.values, names=ratings.index, title='Rating of Apps')
fig.show()

fig = px.pie(labels=ratings.index, values=ratings.values, names=ratings.index, title='Rating of Apps')
fig.update_traces(textposition='outside', textinfo='percent+label')
fig.show()

fig = px.pie(labels=ratings.index, values=ratings.values, names=ratings.index, title='Rating of Apps', hole=0.6)
fig.update_traces(textposition='outside', textinfo='percent+label')
fig.show()

"""# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install?

Check the datatype of the Installs column.

Count the number of apps at each level of installations.

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.
"""

df_apps_clean.describe()

df_apps_clean.info()

df_apps_clean[["App", "Installs"]].groupby("Installs").count()

df_apps_clean["Installs"] = df_apps_clean["Installs"].str.replace(',', '')
df_apps_clean

df_apps_clean["Installs"] = pd.to_numeric(df_apps_clean["Installs"])
df_apps_clean.info()

"""# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

"""

df_apps_clean["Price"] = df_apps_clean["Price"].str.replace("$", "")
df_apps_clean["Price"] = pd.to_numeric(df_apps_clean["Price"])
df_apps_clean

"""### The most expensive apps sub $250"""

df_apps_clean = df_apps_clean[df_apps_clean["Price"] <= 250]
print(df_apps_clean.shape)

df_apps_clean.sort_values("Price", ascending=False).head(20)

"""### Highest Grossing Paid Apps (ballpark estimate)"""

df_apps_clean["Revenue_Estimate"] = df_apps_clean["Installs"] * df_apps_clean['Price']
df_apps_clean.sort_values("Revenue_Estimate", ascending=False).head(10)

"""# Plotly Bar Charts & Scatter Plots: Analysing App Categories"""

df_apps_clean.Category.nunique()
top10category = df_apps_clean.Category.value_counts().head(10)
top10category





"""### Vertical Bar Chart - Highest Competition (Number of Apps)"""

fig = px.bar(x=top10category.index, y=top10category.values)
fig.show()

"""### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)"""

category_installs = df_apps_clean.groupby("Category").agg({"Installs" : pd.Series.sum}).head(10)
category_installs.sort_values("Installs", ascending=False, inplace=True)

fig = px.bar(x=category_installs.index, y=category_installs.Installs)
fig.show()

h_bar = px.bar(x = category_installs.Installs,
               y = category_installs.index,
               orientation='h',
               title='Category Popularity')

h_bar.update_layout(xaxis_title='Number of Downloads', yaxis_title='Category')
h_bar.show()

"""### Category Concentration - Downloads vs. Competition

**Challenge**:
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this.

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')
"""

category_app_installs = df_apps_clean.groupby("Category").agg({"Installs" : pd.Series.sum, "App": pd.Series.count})
category_app_installs.sort_values("App", ascending=False, inplace=True)
category_app_installs

fig = px.scatter(category_app_installs,
                 x=category_app_installs.App,
                 y=category_app_installs.Installs,
                 color=category_app_installs.Installs,
                 title='Category Concentration',
                 size='App',
                 hover_name=category_app_installs.index,
                 labels=dict(Installs="Installs", App = "Number of Apps (Lower=More Concentrated)"),
                 size_max=25,
                 width=1210, height=720)

fig.update_layout(yaxis=dict(type='log'))

fig.show()

"""# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

"""

df_apps_clean['Genres'].value_counts()

genre_app = df_apps_clean['Genres'].str.split(';', expand=True).stack(future_stack=True).reset_index(drop = True).value_counts()

"""# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data?

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/).

* Find a way to set the colour scale using the color_continuous_scale parameter.
* Find a way to make the color axis disappear by using coloraxis_showscale.
"""

genre_app = genre_app.sort_values(ascending=False).head(15)

fig = px.bar(genre_app, x=genre_app.index, y=genre_app.values, color=genre_app.values, color_continuous_scale="Agsunset",
             labels=dict(Installs="Number of Apps", App = "Genre"),
             width=1210, height=720)
fig.update_layout(coloraxis_showscale=False)
fig.show()

